In [5]:
import numpy as np
X = np.array(([2, 9], [1, 5], [3, 6]), dtype=float)
print(X)
y = np.array(([92], [86], [89]), dtype=float)
print(y)
X = X/np.amax(X, axis=0)
y = y/100

class Neural_Network(object):
    def __init__(self):
        self.inputSize = 2
        self.outputSize = 1
        self.hiddenSize = 3
        self.W1 = np.random.randn(self.inputSize, self.hiddenSize)
        self.W2 = np.random.randn(self.hiddenSize, self.outputSize)

    def forward(self, X):
        self.z = np.dot(X, self.W1)
        self.z2 = self.sigmoid(self.z)
        self.z3 = np.dot(self.z2, self.W2)
        o = self.sigmoid(self.z3) 
        return o 

    def sigmoid(self, s):
        return 1/(1+np.exp(-s))

    def sigmoidPrime(self, s):
        return s * (1 - s)
    
    def backward(self, X, y, o):
        self.o_error = y - o
        self.o_delta = self.o_error*self.sigmoidPrime(o)
        self.z2_error = self.o_delta.dot(self.W2.T)
        self.z2_delta = self.z2_error*self.sigmoidPrime(self.z2)
        self.W1 += X.T.dot(self.z2_delta)
        self.W2 += self.z2.T.dot(self.o_delta)

    def train (self, X, y):
        o = self.forward(X)
        self.backward(X, y, o)

NN = Neural_Network()
for i in range(1000):
       print ("\nInput: \n" + str(X))
       print ("\nActual Output: \n" + str(y))
       print ("\nPredicted Output: \n" + str(NN.forward(X)))
       print ("\nLoss: \n" + str(np.mean(np.square(y - NN.forward(X)))))
       NN.train(X, y)




[[2. 9.]
 [1. 5.]
 [3. 6.]]
[[92.]
 [86.]
 [89.]]

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.36694993]
 [0.39004903]
 [0.42805819]]

Loss: 
0.24670284188582955

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.4228875 ]
 [0.4442663 ]
 [0.47661958]]

Loss: 
0.19694624029157837

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.47381574]
 [0.49386741]
 [0.52003853]]

Loss: 
0.1566683199634787

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.51971757]
 [0.53825043]
 [0.5590062 ]]

Loss: 
0.12443523618498721

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666


Predicted Output: 
[[0.89278775]
 [0.87079081]
 [0.88935163]]

Loss: 
0.0002857894923464106

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89299719]
 [0.87098177]
 [0.88954843]]

Loss: 
0.00028331837899348

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89319903]
 [0.87116549]
 [0.88973807]]

Loss: 
0.0002810096461019988

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89339359]
 [0.87134228]
 [0.88992085]]

Loss: 
0.00027885146340254777

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89358118]
 [0.8715124 ]
 [0.89009705]]

Loss: 
0.00027683291889895234

Input: 
[[0.66666667 1.   

 [0.89494398]]

Loss: 
0.00023926894839784553

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89883378]
 [0.87564809]
 [0.89495487]]

Loss: 
0.00023914077238353535

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89884649]
 [0.87564968]
 [0.89496548]]

Loss: 
0.00023901308708908122

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.8988589 ]
 [0.87565098]
 [0.8949758 ]]

Loss: 
0.00023888587097369214

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89887103]
 [0.87565201]
 [0.89498585]]

Loss: 
0.0002387591038367702

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.        

 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89942419]
 [0.87526087]
 [0.89537478]]

Loss: 
0.0002283820982085023

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89942801]
 [0.87525451]
 [0.89537682]]

Loss: 
0.00022827237490344503

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89943181]
 [0.87524815]
 [0.89537884]]

Loss: 
0.00022816278190121678

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.8994356 ]
 [0.87524178]
 [0.89538084]]

Loss: 
0.0002280533189298079

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89943937]
 [0.8752354 ]
 [


Predicted Output: 
[[0.89978019]
 [0.87459634]
 [0.89554034]]

Loss: 
0.0002175297473831657

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89978337]
 [0.87459025]
 [0.89554166]]

Loss: 
0.0002174324991639675

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89978655]
 [0.87458416]
 [0.89554298]]

Loss: 
0.00021733535932085503

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89978972]
 [0.87457808]
 [0.8955443 ]]

Loss: 
0.00021723832767233897

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.89979289]
 [0.874572  ]
 [0.89554562]]

Loss: 
0.00021714140403728273

Input: 
[[0.66666667 1.


Loss: 
0.00020831339316663508

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.90009207]
 [0.87401071]
 [0.8956615 ]]

Loss: 
0.00020822613940433424

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.90009507]
 [0.87400521]
 [0.89566258]]

Loss: 
0.00020813897753084923

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.90009807]
 [0.87399971]
 [0.89566366]]

Loss: 
0.00020805190739711456

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.90010107]
 [0.87399422]
 [0.89566474]]

Loss: 
0.00020796492885435114

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]



Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.9004136 ]
 [0.87343767]
 [0.89576848]]

Loss: 
0.00019915780601608945

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.90041644]
 [0.87343275]
 [0.89576934]]

Loss: 
0.00019907990278128843

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.90041929]
 [0.87342783]
 [0.8957702 ]]

Loss: 
0.0001990020765329245

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.90042213]
 [0.87342291]
 [0.89577107]]

Loss: 
0.0001989243271506637

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]



Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.90070463]
 [0.87294603]
 [0.89584971]]

Loss: 
0.00019137680283766366

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.90070733]
 [0.87294159]
 [0.8958504 ]]

Loss: 
0.00019130636681461894

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.90071003]
 [0.87293715]
 [0.89585108]]

Loss: 
0.0001912359963056143

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.90071272]
 [0.87293271]
 [0.89585176]]

Loss: 
0.00019116569121186173

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.90071542]
 [0.87292828]
 [0.89585244]]

Loss: 
0.00


Predicted Output: 
[[0.90096847]
 [0.87252175]
 [0.89591046]]

Loss: 
0.00018464221098778199

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.90097105]
 [0.8725177 ]
 [0.89591099]]

Loss: 
0.00018457786552316798

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.90097362]
 [0.87251366]
 [0.89591152]]

Loss: 
0.00018451357654081737

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.9009762 ]
 [0.87250962]
 [0.89591205]]

Loss: 
0.0001844493439584719

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.90097877]
 [0.87250559]
 [0.89591258]]

Loss: 
0.00018438516769401809

Input: 
[[0.66666667 1


Predicted Output: 
[[0.901208  ]
 [0.87215369]
 [0.89595489]]

Loss: 
0.0001787706544765183

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.90121047]
 [0.87214998]
 [0.89595529]]

Loss: 
0.00017871132714350943

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.90121294]
 [0.87214628]
 [0.89595569]]

Loss: 
0.0001786520491004813

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.9012154 ]
 [0.87214258]
 [0.8959561 ]]

Loss: 
0.00017859282027800276

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.90121786]
 [0.87213888]
 [0.8959565 ]]

Loss: 
0.0001785336406067563

Input: 
[[0.66666667 1. 


Predicted Output: 
[[0.90143041]
 [0.87182616]
 [0.89598695]]

Loss: 
0.00017351047733958811

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.90143277]
 [0.87182274]
 [0.89598724]]

Loss: 
0.00017345540869649127

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.90143514]
 [0.87181933]
 [0.89598754]]

Loss: 
0.0001734003834369011

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.90143751]
 [0.87181592]
 [0.89598783]]

Loss: 
0.00017334540150165084

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

Predicted Output: 
[[0.90143987]
 [0.87181252]
 [0.89598812]]

Loss: 
0.00017329046283167432

Input: 
[[0.66666667 1