In [44]:
from sklearn.datasets import fetch_20newsgroups 
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import classification_report 
import numpy as np

categories = ['alt.atheism', 'soc.religion.christian','comp.graphics', 'sci.med'] 
twenty_train = fetch_20newsgroups(subset='train',categories=categories,shuffle=True)
twenty_test = fetch_20newsgroups(subset='test',categories=categories,shuffle=True)

from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer()
X_train_tf = count_vect.fit_transform(twenty_train.data)

from sklearn.feature_extraction.text import TfidfTransformer
tfidf_transformer = TfidfTransformer()
X_train_tfidf = tfidf_transformer.fit_transform(X_train_tf)
X_train_tfidf.shape

from sklearn.naive_bayes import MultinomialNB 
from sklearn.metrics import accuracy_score
from sklearn import metrics
mod = MultinomialNB()
mod.fit(X_train_tfidf, twenty_train.target)

X_test_tf = count_vect.transform(twenty_test.data) 
X_test_tfidf = tfidf_transformer.transform(X_test_tf) 
predicted = mod.predict(X_test_tfidf)
print("Accuracy:", accuracy_score(twenty_test.target, predicted)) 
print(classification_report(twenty_test.target,predicted,target_names=twenty_test.target_names)) 
print("confusion matrix is \n",metrics.confusion_matrix(twenty_test.target, predicted))


Accuracy: 0.8348868175765646
                        precision    recall  f1-score   support

           alt.atheism       0.97      0.60      0.74       319
         comp.graphics       0.96      0.89      0.92       389
               sci.med       0.97      0.81      0.88       396
soc.religion.christian       0.65      0.99      0.78       398

              accuracy                           0.83      1502
             macro avg       0.89      0.82      0.83      1502
          weighted avg       0.88      0.83      0.84      1502

confusion matrix is 
 [[192   2   6 119]
 [  2 347   4  36]
 [  2  11 322  61]
 [  2   2   1 393]]


In [25]:
data = []
for x in dataset:
    data.append([ageEnum[x[0]],genderEnum[x[1]],familyHistoryEnum[x[2]],dietEnum[x[3]],lifeStyleEnum[x[4]],cholesterolEnum[x[5]],heartDiseaseEnum[x[6]]])
data = np.array(data)
print(data)

[[0 0 0 1 3 0 0]
 [0 1 0 1 3 0 0]
 [1 0 1 0 2 1 0]
 [4 0 0 1 3 2 1]
 [3 1 0 0 0 2 1]
 [2 0 0 1 1 0 0]
 [4 0 0 0 2 0 0]
 [0 0 0 1 3 0 0]
 [3 1 0 0 0 2 1]
 [1 1 1 0 0 2 0]
 [4 1 1 1 2 0 0]
 [4 0 0 1 3 2 1]
 [2 1 1 0 0 0 1]
 [2 0 0 1 1 0 0]
 [3 1 0 0 0 1 1]
 [0 0 0 0 0 2 0]
 [1 1 1 1 2 1 0]
 [3 1 0 1 0 1 1]
 [4 0 0 1 3 2 1]]


In [26]:
N = len(data)
p_age = bp.nodes.Dirichlet(1.0 * np.ones(5))
age = bp.nodes.Categorical(p_age, plates=(N,))
age.observe(data[:,0])
p_gender = bp.nodes.Dirichlet(1.0 * np.ones(2))
gender = bp.nodes.Categorical(p_gender, plates=(N,))
gender.observe(data[:,1])
p_familyhistory = bp.nodes.Dirichlet(1.0 * np.ones(2))
familyhistory = bp.nodes.Categorical(p_familyhistory, plates=(N,))
familyhistory.observe(data[:,2])
p_diet = bp.nodes.Dirichlet(1.0 * np.ones(3))
diet = bp.nodes.Categorical(p_diet, plates=(N,))
diet.observe(data[:,3])
p_lifestyle = bp.nodes.Dirichlet(1.0 * np.ones(4))
lifestyle = bp.nodes.Categorical(p_lifestyle, plates=(N,))
lifestyle.observe(data[:,4])
p_cholesterol = bp.nodes.Dirichlet(1.0 * np.ones(3))
cholesterol = bp.nodes.Categorical(p_cholesterol, plates=(N,))
cholesterol.observe(data[:,5])
p_heartdisease = bp.nodes.Dirichlet(np.ones((2, 5, 2, 2, 3, 4, 3)))
heartdisease = bp.nodes.MultiMixture([age, gender, familyhistory, diet, lifestyle, cholesterol],
                                     bp.nodes.Categorical, p_heartdisease)
heartdisease.observe(data[:,6])
p_heartdisease.update()



ValueError: No automatic conversion from CategoricalMoments to CategoricalMoments with different number of categories

Skipping record ['SuperSeniorCitizen', 'Male', 'Yes', 'Medium', 'Sedetary', 'High', 'Yes'], invalid value found


NameError: name 'heartDisease' is not defined